### PR TITLE
User/orilevari/dashboard free dim input

### PR DESCRIPTION
**Pull request by orilevari**
Source copy newest commit of WinMLRunner to be consumed by WinMLDashboard and modify required File loading paths to register the custom debug operator. This change was originally motivated by the inability to evaluate models with free input dimensions due to using old WinMLRunner sources.

### CODE REVIEW

**Comment by orilevari** [comment]
This pull request does another source copy of WinMLRunner for the purposes of having a flavor that can consume the Debug operator.

**Comment by zhangxiang1993** [comment]
Did we decide to copy WinmlRunner source code to WinmlDashboard? Could we do a git submodule?

**Comment by orilevari** [comment]
As we discussed in the sync up last week, this pr unblocks the free dim bug and continues the previous solution of source copying. Investigation into a potential better overall solution (i.e flag in WinMLRunner or git submodule) should be decoupled from fixing this bug.

**Comment by zhangxiang1993** [comment]
I'll approve this for the current solution as discussed, and please file a task/bug for Investigation into a potential better overall solution

**Pull request closed without merging**
